# Generated by Django 4.2.4 on 2023-09-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
            ],
        ),
    ]
