# Generated by Django 4.2.5 on 2023-09-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='hello',
        ),
    ]
